name: TypeScript CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unitTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 8.8.0

      - name: Install dependencies
        run: |
          pnpm install

      - name: Run tests
        run: |
          pnpm run coverage
          ls -al coverage

      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: 1ebdc4b127391a8acbc3420eb585961e4e0846de

      - name: Upload coverage to codecov
        run: curl -s https://codecov.io/bash | bash
